baseurl = "https://www.kittyr.com/"
title = "Kitty R. around the world"
theme = "future-imperfect"
preserveTaxonomyNames = true
paginate = 3
disqusShortname = "kittyr"
googleAnalytics = "UA-110859141-1"
pluralizeListTitles = false

[params]
  # Sets the meta tag description
  description          = "Kitty R. was created in 2015 during a hitch-hiking trip with Grandpa T. through Morocco. Before that time, she had already been traveling quite a lot; from Scandinavia to the Iberian Peninsula and Asia Minor."
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle          = "Kitty R. Adventures"
  # Sets where "View More Posts" links
  viewMorePostLink     = "/blog/"

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = false
  # Sets RSS icons to appear on the sidebar with the social media buttons
  rssAppearAtTop       = true
  rssAppearAtBottom    = false
  # Sets Social Media icons to appear on the sidebar
  socialAppearAtTop    = true
  socialAppearAtBottom = false
  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = false
  # Sets Estimated Reading Time to appear in post headers
  includeReadingTime   = false 
  # Sets the Favicon and Version for the site. Default support is for
  # apple-touch-icon-precomposed.png, favicon.png, favicon.ico, and mstile.png.
  # These are stored in the favicon folder. See the following for more information:
  # https://github.com/audreyr/favicon-cheat-sheet
  loadFavicon          = false
  faviconVersion       = ""
  # Sets Social Share links to appear on posts
  socialShare          = true
  # Load custom CSS or JavaScript files. The variable is an array so that you
  # can load multiple files if necessary. You can also load the standard theme
  # files by adding the value, "default".
  # customCSS            = ["default", "/path/to/file"]
  # customJS             = ["default", "/path/to/file"]
  customCSS            = ["default"]
  customJS             = ["default"]

# Disqus will take priority over Staticman (github.com/eduardoboucas/staticman)
# due to its ease of use. Feel free to check out both and decide what you would
# prefer to use. See Staticman.yml for additional settings.
[params.staticman]
  # Sets Statiman to be active
  staticman = false
  # Sets the location for Staticman to connect to
  username  = ""
  repo      = ""
  branch    = ""

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
[params.intro]
  header    = "Kitty R. adventures around the world"

  paragraph = ""

  about     = "-"

  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.
  [params.intro.pic]
    src       = "/img/main/logo.jpg"
    # Sets Image to be a cirlce
    circle    = false
    # Sets Image to be Future Imperfect's hexagon
    imperfect = false
    width     = ""
    alt       = "Kitty R. pic"

[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
    sidebar = 5

# Sets the default language for multilanguage use.
DefaultContentLanguage = "en"

[Languages]
    [Languages.en]
	languageCode = "en-GB"
        LanguageName = "English"
        weight = 1
        
            # Sets the menu items in the navigation bar
            # Identifier prepends a Font Awesome icon to the menu item
            # Each language has its own menu.
            [[Languages.en.menu.main]]
                name = "Home"
                url = "/"
                identifier = "fa fa-home"
                weight = 1

            [[Languages.en.menu.main]]
                name = "Blog"
                url = "/blog/"
                identifier = "fa fa-newspaper-o"
                weight = 2 

            [[Languages.en.menu.main]]
                name = "About"
                url = "/about/"
                identifier = "fa fa-id-card-o"
                weight = 4

            [[Languages.en.menu.main]]
                name = "Destinations"
                url = "/destinations/"
                identifier = "fa fa-sitemap"
                weight = 3 

            [[Languages.en.menu.main]]
                name = "Contact"
                url = "/contact/"
                identifier = "fa fa-envelope-o"
                weight = 6

    [Languages.pl]
	languageCode = "pl"
        LanguageName = "Polskie"
        title = "Kicia R na całym świecie"
        description = "Kicia R. powstala w 2015 roku w trakcie kolejnej autostopowej podróży z Dziadkiem T. po Maroku. Kicia R. podróżowała całkiem sporo jeszcze nim powstała... od Skandynawii po Polwysep Iberyjski czy też Azję Mniejszą. Z plecakiem, stopem, śpiąc gdziekolwiek. Teraz rusza dalej w świat I postanowiła podzielić się swoimi małymi przygodami."
        weight = 2
    
            [[Languages.pl.menu.main]]
                name = "Home"
                url = "/"
                identifier = "fa fa-home"
                weight = 1

            [[Languages.pl.menu.main]]
                name = "Blog"
                url = "/blog/"
                identifier = "fa fa-newspaper-o"
                weight = 2  

            [[Languages.pl.menu.main]]
                name = "O mnie"
                url = "/about/"
                identifier = "fa fa-id-card-o"
                weight = 4

            [[Languages.pl.menu.main]]
                name = "Destynacje"
                url = "/destinations/"
                identifier = "fa fa-sitemap"
                weight = 3

            [[Languages.pl.menu.main]]
                name = "Kontakt"
                url = "/contact/"
                identifier = "fa fa-envelope-o"
                weight = 6


# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Coding Communities
  github          = "blgo/travel-blog"
  gitlab          = ""
  stackoverflow   = "" # User Number
  bitbucket       = ""
  jsfiddle        = ""
  codepen         = ""
  # Visual Art Communities
  deviantart      = ""
  flickr          = ""
  behance         = ""
  dribbble        = ""
  # Publishing Communities
  wordpress       = ""
  medium          = ""
  # Professional/Business Oriented Communities
  linkedin        = ""
  foursquare      = ""
  xing            = ""
  slideshare      = ""
  # Social Networks
  facebook        = "kittyRadventures"
  googleplus      = ""
  reddit          = ""
  quora           = ""
  youtube         = ""
  vimeo           = ""
  whatsapp        = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat          = ""
    qq              = "" # User ID Number
  instagram       = ""
  tumblr          = ""
  twitter         = ""
  skype           = ""
  snapchat        = ""
  pinterest       = ""
  telegram        = ""
  vine            = ""
  # Email
  email           = "kittyrtravels@gmail.com"

[taxonomies]
  destination = "destinations"
